### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by vovafes** [useragents/Snapchat-Snapscore-Botter#29]
Traceback (most recent call last):
  File "/Users/vovafes/Desktop/Snapchat-Snapscore-Botter-main/main.py", line 137, in <module>
    obj.main()
  File "/Users/vovafes/Desktop/Snapchat-Snapscore-Botter-main/main.py", line 111, in main
    ctypes.windll.kernel32.SetConsoleTitleW("Snapchat Score Botter | Developed by @useragents on Github")
AttributeError: module 'ctypes' has no attribute 'windll'

**Comment by useragents** [comment]
You can remove any lines using the class `ctypes` as your OS is not supported by it. `ctypes` is not required for this script to work.
