### ISSUE TITLE
Error in termux

### ISSUE THREAD

**Issue by naman77s** [useragents/Snapchat-Snapscore-Botter#31]
┌─[PXD@termux]─[~/Snapchat-Snapscore-Botter]
└──╼ ❯❯❯ python3 main.py
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/Snapchat-Snapscore-Botter/main.py", line 3, in <module>
    import ctypes, pyautogui, keyboard, os, time
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/pyautogui/__init__.py", line 249, in <module>
    import mouseinfo
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/mouseinfo/__init__.py", line 223, in <module>
    _display = Display(os.environ['DISPLAY'])
  File "/data/data/com.termux/files/usr/lib/python3.10/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'DISPLAY'

How can i solve this?

**Comment by useragents** [comment]
Only works on Windows.
